export const sizing = {
    radius: [{text: '\{ borderRadius: Variables.variables.sizing.Mode1[cornerRadius050] \}',
        varName: 'cornerRadius050',
    },{text: '\{ borderRadius: Variables.variables.sizing.Mode1[cornerRadius100] \}',
        varName: 'cornerRadius100',
    },{text: '\{ borderRadius: Variables.variables.sizing.Mode1[cornerRadius150] \}',
        varName: 'cornerRadius150',
    },{text: '\{ borderRadius: Variables.variables.sizing.Mode1[cornerRadius200] \}',
        varName: 'cornerRadius200',
    },{text: '\{ borderRadius: Variables.variables.sizing.Mode1[cornerRadius250] \}',
        varName: 'cornerRadius250',
    },{text: '\{ borderRadius: Variables.variables.sizing.Mode1[cornerRadius300] \}',
        varName: 'cornerRadius300',
    }],
    paddings: [{text: '\{ padding: Variables.variables.sizing.Mode1[padding100] \}',
        varName: 'padding100',
    },{text: '\{ padding: Variables.variables.sizing.Mode1[padding200] \}',
        varName: 'padding200',
    },{text: '\{ padding: Variables.variables.sizing.Mode1[padding250] \}',
        varName: 'padding250',
    },{text: '\{ padding: Variables.variables.sizing.Mode1[padding300] \}',
        varName: 'padding300',
    },{text: '\{ padding: Variables.variables.sizing.Mode1[padding400] \}',
        varName: 'padding400',
    },{text: '\{ padding: Variables.variables.sizing.Mode1[padding500] \}',
        varName: 'padding500',
    },{text: '\{ padding: Variables.variables.sizing.Mode1[padding600] \}',
        varName: 'padding600',
    },{text: '\{ padding: Variables.variables.sizing.Mode1[padding800] \}',
        varName: 'padding800',
    },{text: '\{ padding: Variables.variables.sizing.Mode1[padding1000] \}',
        varName: 'padding1000',
    },{text: '\{ padding: Variables.variables.sizing.Mode1[padding1200] \}',
        varName: 'padding1200',
    }],
}