export const sizing = {
    radius: [
    {text: 'border-radius: var(--sizing-mode-1-corner-radius-100)',
        varName: '--sizing-mode-1-corner-radius-100',
    },{text: 'border-radius: var(--sizing-mode-1-corner-radius-200)',
        varName: '--sizing-mode-1-corner-radius-200',
    },{text: 'border-radius: var(--sizing-mode-1-corner-radius-150)',
        varName: '--sizing-mode-1-corner-radius-150',
    },{text: 'border-radius: var(--sizing-mode-1-corner-radius-300)',
        varName: '--sizing-mode-1-corner-radius-300',
    },{text: 'border-radius: var(--sizing-mode-1-corner-radius-050)',
        varName: '--sizing-mode-1-corner-radius-050',
    },{text: 'border-radius: var(--sizing-mode-1-corner-radius-250)',
        varName: '--sizing-mode-1-corner-radius-250',
    }],
    paddings: [
        {text: 'padding: var(--sizing-mode-1-padding-100)',
            varName: '--sizing-mode-1-padding-100',
        },{text: 'padding: var(--sizing-mode-1-padding-200)',
            varName: '--sizing-mode-1-padding-200',
        },{text: 'padding: var(--sizing-mode-1-padding-300)',
            varName: '--sizing-mode-1-padding-300',
        },{text: 'padding: var(--sizing-mode-1-padding-400)',
            varName: '--sizing-mode-1-padding-400',
        },{text: 'padding: var(--sizing-mode-1-padding-250)',
            varName: '--sizing-mode-1-padding-250',
        },{text: 'padding: var(--sizing-mode-1-padding-800)',
            varName: '--sizing-mode-1-padding-800',
        },{text: 'padding: var(--sizing-mode-1-padding-500)',
            varName: '--sizing-mode-1-padding-500',
        },{text: 'padding: var(--sizing-mode-1-padding-600)',
            varName: '--sizing-mode-1-padding-600',
        },{text: 'padding: var(--sizing-mode-1-padding-1000)',
            varName: '--sizing-mode-1-padding-1000',
        },{text: 'padding: var(--sizing-mode-1-padding-1200)',
            varName: '--sizing-mode-1-padding-1200',
        },
    ],
};