export const typography = [
    {text: '<div className=desktop-label-medium-bold />',
        varName: 'desktop-label-medium-bold',
    },{text: '<div className=desktop-label-large-book />',
        varName: 'desktop-label-large-book',
    },{text: '<div className=desktop-label-small-book />',
        varName: 'desktop-label-small-book',
    },{text: '<div className=desktop-h4 />',
        varName: 'desktop-h4',
    },{text: '<div className=desktop-h3 />',
        varName: 'desktop-h3',
    },{text: '<div className=desktop-h2 />',
        varName: 'desktop-h2',
    },{text: '<div className=desktop-h1 />',
        varName: 'desktop-h1',
    },{text: '<div className=desktop-paragraph-basic-book />',
        varName: 'desktop-paragraph-basic-book',
    },{text: '<div className=desktop-input />',
        varName: 'desktop-input',
    },{text: '<div className=desktop-paragraph-large-book />',
        varName: 'desktop-paragraph-large-book',
    },{text: '<div className=desktop-label-medium-medium />',
        varName: 'desktop-label-medium-medium',
    },{text: '<div className=desktop-label-large-bold />',
        varName: 'desktop-label-large-bold',
    },{text: '<div className=desktop-label-small-medium />',
        varName: 'desktop-label-small-medium',
    },{text: '<div className=desktop-label-medium-book />',
        varName: 'desktop-label-medium-book',
    },{text: '<div className=desktop-label-xsmall-label-xsmall />',
        varName: 'desktop-label-xsmall-label-xsmall',
    },{text: '<div className=desktop-paragraph-large-bold />',
        varName: 'desktop-paragraph-large-bold',
    },{text: '<div className=desktop-label-small-bold />',
        varName: 'desktop-label-small-bold',
    },{text: '<div className=desktop-h6 />',
        varName: 'desktop-h6',
    },{text: '<div className=desktop-h5 />',
        varName: 'desktop-h5',
    },{text: '<div className=desktop-paragraph-basic-bold />',
        varName: 'desktop-paragraph-basic-bold',
    },{text: '<div className=desktop-label-medium />',
        varName: 'desktop-label-medium',
    },{text: '<div className=desktop-label-xsmall-bold />',
        varName: 'desktop-label-xsmall-bold',
    }
    //,{text: '<div className=',
    //     varName: '',
    // },
]