export const typography = [
    {text: 'style={{ ...desktopLabelMediumBold }}',
        varName: 'desktopLabelMediumBold',
    },{text: 'style={{ ...desktopLabelLargeBook }}',
        varName: 'desktopLabelLargeBook',
    },{text: 'style={{ ...desktopLabelSmallBook }}',
        varName: 'desktopLabelSmallBook',
    },{text: 'style={{ ...desktopH4 }}',
        varName: 'desktopH4',
    },{text: 'style={{ ...desktopH3 }}',
        varName: 'desktopH3',
    },{text: 'style={{ ...desktopH2 }}',
        varName: 'desktopH2',
    },{text: 'style={{ ...desktopH1 }}',
        varName: 'desktopH1',
    },{text: 'style={{ ...desktopParagraphBasicBook }}',
        varName: 'desktopParagraphBasicBook',
    },{text: 'style={{ ...desktopInput }}',
        varName: 'desktopInput',
    },{text: 'style={{ ...desktopParagraphLargeBook }}',
        varName: 'desktopParagraphLargeBook',
    },{text: 'style={{ ...desktopLabelMediumMedium }}',
        varName: 'desktopLabelMediumMedium',
    },{text: 'style={{ ...desktopLabelLargeBold }}',
        varName: 'desktopLabelLargeBold',
    },{text: 'style={{ ...desktopLabelSmallMedium }}',
        varName: 'desktopLabelSmallMedium',
    },{text: 'style={{ ...desktopLabelMediumBook }}',
        varName: 'desktopLabelMediumBook',
    },{text: 'style={{ ...desktopLabelXsmallLabelXsmall }}',
        varName: 'desktopLabelXsmallLabelXsmall',
    },{text: 'style={{ ...desktopParagraphLargeBold }}',
        varName: 'desktopParagraphLargeBold',
    },{text: 'style={{ ...desktopLabelSmallBold }}',
        varName: 'desktopLabelSmallBold',
    },{text: 'style={{ ...desktopH6 }}',
        varName: 'desktopH6',
    },{text: 'style={{ ...desktopH5 }}',
        varName: 'desktopH5',
    },{text: 'style={{ ...desktopParagraphBasicBold }}',
        varName: 'desktopParagraphBasicBold',
    },{text: 'style={{ ...desktopLabelMedium }}',
        varName: 'desktopLabelMedium',
    },{text: 'style={{ ...desktopLabelXsmallBold }}',
        varName: 'desktopLabelXsmallBold',
    }
]